name: Test in a JS Workflow
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    
    - name: Load Application Default Credentials
      run: echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/sa.json && export GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
      
    - name: Install Sops
      run: wget https://github.com/mozilla/sops/releases/download/3.4.0/sops_3.4.0_amd64.deb && sudo dpkg -i sops_3.4.0_amd64.deb
    
    - name: Decrypt secrets
      run: sops --decrypt config/secrets/ci.enc.yml > config/secrets/ci.yml
       
    
    - name: Dump secrets
      run: cat config/secrets/ci.yml
